# aria2.conf
# Inspired by https://gist.github.com/ifyour/2be0055adbaea83881aacaab905afd43

# falloc is faster, but fails on old filesystems such as ext3 or FAT32.
# Thus, it's easier/better to just not preallocate anything at all.
# Fragmentation isn't an issue in modern days.
# Default is prealloc, which is extremely slow for large files, and causes unnecessary wear on flash storage.
# file-allocation = falloc
file-allocation = none

# The default seed-ratio is 1.0, which is too long.
#seed-ratio = 0.125
# Let's set a maximum time of one minute to seed.
# If I'm interested in seeding this forever, I should use another tool such as qbittorrent.
seed-time = 1

# Default is 1
max-connection-per-server = 2

# Default is 20M
# min-split-size = 20M

# Default is 5.
# split = 5
